# engine/stack.py
from typing import List, Optional, Dict, Any
from effects.effect_manager import EffectManager
from models.stack_item import StackItem, StackItemType, StackItemStatus


class StackManager:
    """
    Controls the MTG stack.

    Responsibilities:
    - Add spells and abilities to the stack.
    - Resolve the top object.
    - Apply effects.
    - Move resolved spells to the graveyard.
    """

    def __init__(self, game_state):
        self.game_state = game_state
        self.effect_manager = EffectManager(game_state)

    # ==================================================
    # Stack Operations
    # ==================================================

    def push(self, stack_item: StackItem) -> None:
        """
        Place a spell or ability onto the stack.
        """
        self.game_state.push_stack(stack_item)
        print(f"   📚 Stack: {stack_item.source_name} added ({len(self.game_state.stack)} items)")

    def pop(self) -> Optional[StackItem]:
        """
        Remove and return the top stack object.
        """
        return self.game_state.pop_stack()

    def peek(self) -> Optional[StackItem]:
        """
        Return the top stack object without removing it.
        """
        return self.game_state.peek_stack()

    def is_empty(self) -> bool:
        """
        Return True if the stack is empty.
        """
        return self.game_state.stack_empty()

    def clear(self) -> None:
        """
        Remove every object from the stack.
        """
        self.game_state.clear_stack()

    # ==================================================
    # Resolution
    # ==================================================

    def resolve(self) -> List[Dict[str, Any]]:
        """
        Resolve the top object on the stack.

        Returns a list of state changes generated by the
        resolved spell or ability.
        """
        stack_item = self.pop()

        if stack_item is None:
            return []

        print(f"   📚 Resolving: {stack_item.source_name}")

        state_changes = []

        # ==================================================
        # Step 1: Check if targets are still legal
        # ==================================================
        if stack_item.has_targets:
            # Check if all targets are still valid
            # In a full implementation, you'd check if targets still exist
            # and are still legal (e.g., creature still on battlefield)
            
            # For now, we'll assume they're legal
            # TODO: Implement full target legality checking
            pass

        # ==================================================
        # Step 2: Apply effects
        # ==================================================
        source = getattr(stack_item, "source", None)
        effects = getattr(stack_item, "effects", [])

        if effects:
            state_changes = self.effect_manager.apply_all(effects, source)
            print(f"   ✅ {stack_item.source_name} resolved with {len(state_changes)} changes")

        # ==================================================
        # Step 3: Move source to appropriate zone
        # ==================================================
        self._move_source_to_zone(stack_item)

        # ==================================================
        # Step 4: Mark as resolved
        # ==================================================
        stack_item.mark_resolved()

        return state_changes

    def resolve_with_fizzle(self, stack_item: StackItem, reason: str) -> List[Dict[str, Any]]:
        """
        Resolve a stack item as fizzled (all targets illegal).
        
        Returns an empty list (no state changes).
        """
        print(f"   ❌ {stack_item.source_name} fizzled: {reason}")
        stack_item.mark_fizzled()
        
        # Move source to graveyard (spell fizzles and goes to graveyard)
        self._move_source_to_zone(stack_item)
        
        return []

    def resolve_single(self, stack_item_id: str) -> List[Dict[str, Any]]:
        """
        Resolve a specific stack item by ID.
        
        Returns state changes for the resolved item.
        """
        # Find the item on the stack
        target_item = None
        for item in self.game_state.stack:
            if hasattr(item, 'stack_item_id') and item.stack_item_id == stack_item_id:
                target_item = item
                break
        
        if not target_item:
            print(f"   ❌ Stack item {stack_item_id} not found")
            return []
        
        # Remove it from the stack (it's at the top if we're resolving)
        # In MTG, only the top item resolves
        if self.peek() == target_item:
            return self.resolve()
        else:
            print(f"   ⚠️ Can only resolve the top item on the stack")
            return []

    # ==================================================
    # Internal Helpers
    # ==================================================

    def _move_source_to_zone(self, stack_item: StackItem) -> None:
        """
        Move the source card to the appropriate zone after resolution.
        
        - Creatures: move to battlefield (already there if cast)
        - Instants/Sorceries: move to graveyard
        - Abilities: source stays on battlefield
        """
        source = getattr(stack_item, "source", None)
        
        if source is None:
            return
        
        # Abilities don't move the source
        if stack_item.is_ability or stack_item.is_triggered_ability:
            return
        
        # Get the player who owns the source
        owner_id = getattr(source, "owner", None)
        if owner_id is None:
            return
        
        player = self.game_state.get_player(owner_id)
        if player is None:
            return
        
        # Check if it's a spell (Instant or Sorcery)
        if hasattr(source, 'is_instant') and source.is_instant():
            # Instant goes to graveyard after resolving
            # But the card is already in hand, not on stack
            # The card was removed from hand when cast
            # So we don't need to move it here
            pass
        
        elif hasattr(source, 'is_sorcery') and source.is_sorcery():
            # Sorcery goes to graveyard after resolving
            # The card was removed from hand when cast
            pass
        
        elif hasattr(source, 'is_creature') and source.is_creature():
            # Creature spell resolves and enters battlefield
            # The card is already on the battlefield from casting
            # Check if it has summoning sickness
            if hasattr(source, 'summoning_sick'):
                source.summoning_sick = True
            
            # Check for ETB triggers
            self._check_etb_triggers(source, player)
        
        # If it's an artifact or enchantment, it stays on battlefield
        # (already there from casting)

    def _check_etb_triggers(self, card, player) -> None:
        """
        Check for Enter the Battlefield triggers.
        """
        if hasattr(card, 'trigger') and card.trigger:
            event = card.trigger.get('event')
            if event == 'ENTER_BATTLEFIELD':
                effect = card.trigger.get('effect')
                if effect:
                    print(f"   🔄 ETB trigger: {card.name}")
                    self.effect_manager.apply(effect, card)

    def _move_to_graveyard(self, stack_item: StackItem) -> None:
        """
        Deprecated: Use _move_source_to_zone instead.
        """
        self._move_source_to_zone(stack_item)

    # ==================================================
    # Information
    # ==================================================

    def size(self) -> int:
        """
        Return the number of objects currently on the stack.
        """
        return len(self.game_state.stack)

    def get_top_item(self) -> Optional[StackItem]:
        """
        Return the top item on the stack without removing it.
        """
        return self.peek()

    def contains(self, stack_item_id: str) -> bool:
        """
        Check if a stack item with the given ID is on the stack.
        """
        for item in self.game_state.stack:
            if hasattr(item, 'stack_item_id') and item.stack_item_id == stack_item_id:
                return True
        return False

    def get_item(self, stack_item_id: str) -> Optional[StackItem]:
        """
        Get a stack item by ID.
        """
        for item in self.game_state.stack:
            if hasattr(item, 'stack_item_id') and item.stack_item_id == stack_item_id:
                return item
        return None

    def __str__(self) -> str:
        """String representation for debugging."""
        if self.is_empty():
            return "Stack is empty"
        items = [item.source_name for item in self.game_state.stack]
        return f"Stack({len(self.game_state.stack)} items: {items})"