from effects.effect_manager import EffectManager


class StackManager:
    """
    Controls the MTG stack.

    Responsibilities:
    - Add spells and abilities to the stack.
    - Resolve the top object.
    - Apply effects.
    - Move resolved spells to the graveyard.
    """

    def __init__(self, game_state):

        self.game_state = game_state

        self.effect_manager = EffectManager(game_state)

    # ==================================================
    # Stack Operations
    # ==================================================

    def push(self, stack_item):
        """
        Place a spell or ability onto the stack.
        """

        self.game_state.push_stack(stack_item)

    def pop(self):
        """
        Remove and return the top stack object.
        """

        return self.game_state.pop_stack()

    def peek(self):
        """
        Return the top stack object without removing it.
        """

        return self.game_state.peek_stack()

    def is_empty(self):
        """
        Return True if the stack is empty.
        """

        return self.game_state.stack_empty()

    def clear(self):
        """
        Remove every object from the stack.
        """

        self.game_state.clear_stack()

    # ==================================================
    # Resolution
    # ==================================================

    def resolve(self):
        """
        Resolve the top object on the stack.

        Returns a list of state changes generated by the
        resolved spell or ability.
        """

        stack_item = self.pop()

        if stack_item is None:
            return []

        state_changes = []

        source = getattr(stack_item, "source", None)

        effects = getattr(stack_item, "effects", [])

        if effects:

            state_changes = self.effect_manager.apply_all(
                effects,
                source
            )

        self._move_to_graveyard(stack_item)

        return state_changes

    # ==================================================
    # Internal Helpers
    # ==================================================

    def _move_to_graveyard(self, stack_item):
        """
        After a spell resolves, place its source card into
        its owner's graveyard.

        Abilities do not move cards.
        """

        source = getattr(stack_item, "source", None)

        if source is None:
            return

        owner_id = getattr(source, "owner", None)

        if owner_id is None:
            return

        player = self.game_state.get_player(owner_id)

        if player is None:
            return

        player.graveyard.add(source)

    # ==================================================
    # Information
    # ==================================================

    def size(self):
        """
        Return the number of objects currently on the stack.
        """

        return len(self.game_state.stack)