from enum import Enum


class MessageType(Enum):

    # Lobby
    PLAYER_READY = "PLAYER_READY"

    # Server Updates
    GAME_STATE_UPDATE = "GAME_STATE_UPDATE"
    GAME_OVER = "GAME_OVER"

    # Setup
    MULLIGAN_CHOICE = "MULLIGAN_CHOICE"

    # Turn
    PHASE_TRANSITION = "PHASE_TRANSITION"

    # Priority
    PRIORITY_GRANT = "PRIORITY_GRANT"
    PRIORITY_PASS = "PRIORITY_PASS"

    # Stack
    STACK_PUSH = "STACK_PUSH"
    STACK_RESOLVE = "STACK_RESOLVE"

    # Gameplay
    CAST_SPELL = "CAST_SPELL"
    PLAY_LAND = "PLAY_LAND"
    ACTIVATE_ABILITY = "ACTIVATE_ABILITY"

    # Combat
    DECLARE_ATTACKERS = "DECLARE_ATTACKERS"
    DECLARE_BLOCKERS = "DECLARE_BLOCKERS"
    ASSIGN_DAMAGE_ORDER = "ASSIGN_DAMAGE_ORDER"
    COMBAT_DAMAGE_RESULT = "COMBAT_DAMAGE_RESULT"

    # Triggered abilities
    TRIGGER_ORDER = "TRIGGER_ORDER"
    TRIGGER_ORDER_RESPONSE = "TRIGGER_ORDER_RESPONSE"

    TRIGGER_CHOICE = "TRIGGER_CHOICE"
    TRIGGER_CHOICE_RESPONSE = "TRIGGER_CHOICE_RESPONSE"

    # Cleanup
    DISCARD = "DISCARD"

    # Misc
    CONCEDE = "CONCEDE"

    PING = "PING"
    PONG = "PONG"

    ERROR = "ERROR"